spring.application.name=reactive-store
server.port=9091

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/store
spring.r2dbc.username=database_user
spring.r2dbc.password=netec123

#prometheus config
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when-authorized